# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ceshi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.anniu = QtWidgets.QPushButton(self.centralwidget)
        self.anniu.setGeometry(QtCore.QRect(200, 220, 141, 111))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.anniu.setFont(font)
        self.anniu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.anniu.setMouseTracking(True)
        self.anniu.setTabletTracking(False)
        self.anniu.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Desktop/.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anniu.setIcon(icon)
        self.anniu.setIconSize(QtCore.QSize(50, 50))
        self.anniu.setCheckable(False)
        self.anniu.setAutoRepeat(False)
        self.anniu.setObjectName("anniu")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 230, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action555 = QtWidgets.QAction(MainWindow)
        self.action555.setObjectName("action555")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action9)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action7)
        self.menu1.addAction(self.action555)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu1.menuAction())

        self.retranslateUi(MainWindow)
        self.anniu.clicked.connect(self.lineEdit.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anniu.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "复制"))
        self.menu1.setTitle(_translate("MainWindow", "1"))
        self.action555.setText(_translate("MainWindow", "555"))
        self.action7.setText(_translate("MainWindow", "7"))
        self.action9.setText(_translate("MainWindow", "9"))
